import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bell, CheckCheck, X } from 'lucide-react';
import { useNotifications } from '../Utils/notificationStore';
export default function NotificationBell(){
  const notifications=useNotifications();const[open,setOpen]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const container=useRef(null);const navigate=useNavigate();
  useEffect(()=>{const close=event=>{if(!container.current?.contains(event.target))setOpen(false);};const escape=event=>{if(event.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[]);
  async function mark(body,href){setBusy(true);setError('');try{await notifications.read(body);if(href){setOpen(false);navigate(href);}}catch{setError('Could not mark this notification as read. Please retry.');}finally{setBusy(false);}}
  return <div ref={container} className="relative"><button aria-label={`Notifications, ${notifications.unread} unread`} aria-expanded={open} onClick={()=>{setOpen(value=>!value);notifications.refresh();}} className="relative flex h-10 w-10 items-center justify-center rounded-xl border border-purple-200 bg-white text-purple-800"><Bell size={19}/>{notifications.unread>0&&<span data-testid="notification-count" className="absolute -right-1 -top-1 min-w-5 rounded-full bg-rose-600 px-1 text-center text-[10px] font-bold leading-5 text-white">{notifications.unread>99?'99+':notifications.unread}</span>}</button>{open&&<section aria-label="Notifications" className="fixed left-3 right-3 top-20 z-[100] max-h-[75vh] overflow-hidden rounded-2xl border border-slate-200 bg-white text-slate-900 shadow-2xl sm:absolute sm:left-auto sm:right-0 sm:top-12 sm:w-96"><div className="flex items-center justify-between border-b p-4"><h2 className="font-bold">What’s new <span className="text-purple-700">({notifications.unread})</span></h2><button aria-label="Close notifications" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="flex justify-between gap-3 px-4 py-3 text-xs"><button disabled={busy||!notifications.unread} onClick={()=>mark({through:notifications.latest})} className="font-bold text-purple-700 disabled:opacity-40"><CheckCheck className="mr-1 inline" size={14}/>Mark all as read</button><button className="text-slate-500" onClick={notifications.refresh}>Refresh</button></div>{(error||notifications.error)&&<p role="alert" className="px-4 py-2 text-xs text-red-700">{error||notifications.error}</p>}<div className="max-h-[52vh] overflow-auto">{notifications.items.map(item=><button disabled={busy} key={item.id} onClick={()=>mark({id:item.id},item.href)} className={`flex w-full items-start gap-3 border-t border-slate-100 p-4 text-left ${item.unread?'bg-purple-50':'bg-white'}`}><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${item.unread?'bg-purple-600':'bg-slate-200'}`}/><span><span className="block text-sm font-semibold">{item.title}</span><time className="mt-1 block text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</time></span></button>)}{!notifications.items.length&&<p className="p-8 text-center text-sm text-slate-500">You’re all caught up. New activity will appear here.</p>}</div><p className="border-t px-4 py-2 text-[10px] text-slate-400">Latest 60 updates · Refreshes every 10 seconds</p></section>}</div>;
}
