import { Link } from 'react-router-dom';
import { BookOpen, Award, Target, ArrowRight } from 'lucide-react';
import useRemote from '../Utils/useRemote';
import DataState from '../Components/DataState';
import LearningShell from './LearningShell';
export default function StudentDashboard() {
  const remote = useRemote('/learning/dashboard', null);
  const data = remote.data;
  return <LearningShell><DataState {...remote} />{data && <div className="space-y-8">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-purple-900 via-indigo-900 to-slate-950 p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-purple-200">Your learning journey</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">Welcome back, {data.user.name.split(' ')[0]}.</h1><p className="mt-3 max-w-xl text-purple-100">One focused lesson at a time. Continue your courses, put your knowledge to work, and earn your next certificate.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#my-courses" className="rounded-xl bg-white px-5 py-3 font-bold text-purple-900">Continue learning</a><a href="#my-results" className="rounded-xl border border-white/25 px-5 py-3 font-semibold">My results</a></div></section>
    <div className="grid gap-4 sm:grid-cols-3">{[{ icon: BookOpen, value: data.courses.length, label: 'Enrolled courses' }, { icon: Target, value: data.courses.reduce((sum, course) => sum + course.progress.completed, 0), label: 'Units completed' }, { icon: Award, value: data.certificates.filter(c => !c.revoked_at).length, label: 'Certificates earned' }].map(({ icon: Icon, value, label }) => <div key={label} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="rounded-xl bg-purple-50 p-3 text-purple-700"><Icon size={24} /></div><div><p className="text-2xl font-black">{value}</p><p className="text-sm text-slate-500">{label}</p></div></div>)}</div>
    <section id="my-courses"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold">My courses</h2><Link className="text-sm font-bold text-purple-700" to="/training-room">Find a new course →</Link></div>{!data.courses.length && <div className="rounded-2xl border border-dashed border-purple-200 bg-white p-10 text-center"><BookOpen className="mx-auto mb-3 text-purple-500" /><h3 className="text-xl font-bold">Your next chapter starts here</h3><p className="mt-2 text-slate-500">Apply for a course. Once the training team approves your enrollment, it will appear here.</p><Link to="/training-room" className="mt-5 inline-block rounded-xl bg-purple-700 px-5 py-3 font-bold text-white">Explore training</Link></div>}<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data.courses.map(course => <article key={course.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{course.image && <img src={course.image} alt="" loading="lazy" className="h-44 w-full object-cover" />}<div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-purple-700">{course.category}</p><h3 className="mt-2 text-xl font-bold">{course.title}</h3><p className="mt-2 text-sm text-slate-500">{course.duration} · {course.level}</p><div className="mt-5 flex justify-between text-sm"><span>{course.progress.completed} / {course.progress.total} units</span><strong>{course.progress.percent}%</strong></div><progress aria-label={`${course.title} progress`} className="my-3 h-2 w-full accent-purple-700" max="100" value={course.progress.percent} /><Link to={`/learn/courses/${course.id}`} className="flex items-center justify-between rounded-xl bg-purple-50 px-4 py-3 font-bold text-purple-800">{course.progress.completed ? 'Continue course' : 'Start your course'}<ArrowRight size={18} /></Link></div></article>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-2"><section id="my-results" className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-4 text-xl font-bold">Assessment results</h2>{!data.attempts.length && <p className="text-slate-500">Complete a unit assessment to see your marks here.</p>}<div className="max-h-96 space-y-3 overflow-auto">{data.attempts.map(attempt => <div key={attempt.id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><Link to={`/learn/assessments/${attempt.assessment_id}`} className="font-semibold">{attempt.title}</Link><p className="text-xs text-slate-500">{attempt.kind === 'exam' ? 'Final exam' : 'Unit assessment'} · {new Date(attempt.submitted_at).toLocaleDateString()}</p></div><strong className={attempt.passed ? 'text-emerald-700' : 'text-amber-700'}>{attempt.score}% <span className="block text-xs font-medium">{attempt.passed ? 'Passed' : 'Keep practicing'}</span></strong></div>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-4 text-xl font-bold">Your certificates</h2>{!data.certificates.length && <p className="text-slate-500">Pass all units and the final exam to unlock your course certificate.</p>}<div className="space-y-3">{data.certificates.map(cert => <div key={cert.code} className="flex items-center gap-4 rounded-xl border border-purple-100 bg-purple-50 p-4"><Award className="shrink-0 text-purple-700" /><div><h3 className="font-bold">{cert.course_title}</h3>{cert.revoked_at ? <p className="text-sm text-red-700">Certificate revoked. Contact your instructor.</p> : <Link className="text-sm font-semibold text-purple-700" to={`/certificates/${cert.code}`}>View, print or save as PDF →</Link>}</div></div>)}</div></section></div>
    {!!data.applications.length && <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="mb-4 text-xl font-bold">Enrollment applications</h2><div className="flex flex-wrap gap-3">{data.applications.map(application => <div key={application.id} className="rounded-xl bg-slate-50 px-4 py-3"><p className="font-semibold">{application.course_title || 'Course unavailable'}</p><p className="text-sm capitalize text-purple-700">{application.status}</p></div>)}</div></section>}
  </div>}</LearningShell>;
}
