CREATE TABLE IF NOT EXISTS admin_notification_emails (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 recipient VARCHAR(254) NOT NULL,
 subject VARCHAR(240) NOT NULL,
 body MEDIUMTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 sent_at TIMESTAMP NULL,
 last_error VARCHAR(500) NULL,
 INDEX(sent_at,id)
);
