// The allowlist drives both API validation and the dashboard editor.
const text = (label, required = false, extra = {}) => ({ label, type: 'text', required, ...extra });
const long = (label, required = false) => text(label, required, { type: 'textarea' });
const number = (label, required = false, max = 2147483647) => text(label, required, { type: 'number', min: 0, max });
const select = (label, options, value) => text(label, true, { type: 'select', options, default: value || options[0] });
const image = label => text(label, false, { type: 'image' });
const email = () => text('Email', true, { type: 'email' });
const list = label => text(label, false, { type: 'list' });
const resources = {
  products: { title: 'Products', public: true, fields: { name: text('Name', true), brand: text('Brand', true), category: text('Category', true), price: number('Price (RWF)', true), old_price: number('Previous price (RWF)'), badge: text('Badge'), rating: number('Rating', false, 5), reviews: number('Review count'), image: image('Product image') } },
  services: { title: 'Services', public: true, fields: { title: text('Title', true), category: text('Category', true), short_description: long('Short description', true), description: long('Description', true), image: image('Image'), icon: text('Icon CSS class'), features: list('Features (one per line)'), active: select('Published', ['1', '0'], '1') } },
  courses: { title: 'Courses', public: true, fields: { title: text('Title', true), slug: text('URL slug', true), category: text('Category', true), level: text('Level', true), duration: text('Duration', true), lessons: number('Lessons'), price: number('Price (RWF)', true), old_price: number('Previous price (RWF)'), description: long('Description', true), overview: long('Overview'), skills: list('Skills (one per line)'), projects: list('Course projects (one per line)'), students: number('Students'), image: image('Course image') } },
  careers: { title: 'Job Listings', table: 'job_openings', public: true, fields: { title: text('Title', true), type: text('Employment type', true), location: text('Location', true), level: text('Experience level', true), description: long('Description', true), skills: list('Skills (one per line)'), responsibilities: list('Responsibilities (one per line)'), active: select('Published', ['1', '0'], '1') } },
  projects: { title: 'Projects', public: true, fields: { title: text('Title', true), category: text('Category', true), description: long('Description', true), client: text('Client'), image: image('Image'), url: text('Project URL', false, { type: 'url' }) } },
  blog: { title: 'Blog Posts', table: 'blog_posts', public: true, fields: { title: text('Title', true), slug: text('URL slug', true), excerpt: long('Excerpt'), content: long('Content', true), author: text('Author'), category: text('Category'), image: image('Image') } },
  testimonials: { title: 'Testimonials', public: true, fields: { name: text('Name', true), role: text('Role / course'), company: text('Company'), content: long('Testimonial', true), rating: number('Rating', false, 5), avatar: image('Avatar') } },
  partners: { title: 'Partners', public: true, fields: { name: text('Name', true), category: text('Category'), website: text('Website', false, { type: 'url' }), logo: image('Logo') } },
  subscribers: { title: 'Subscribers', fields: { email: email() } },
  contacts: { title: 'Contacts', table: 'contact_messages', fields: { name: text('Name', true), email: email(), phone: text('Phone'), subject: text('Subject', true), message: long('Message', true), status: select('Status', ['unread', 'read', 'replied']) } },
  enrollments: { title: 'Enrollments', fields: { user_id: number('User ID'), course_id: text('Course', true, { type: 'relation', resource: 'courses' }), full_name: text('Full name', true), email: email(), phone: text('Phone', true), education: text('Education'), experience: text('Experience'), mode: text('Training mode'), start_period: text('Start period'), message: long('Message'), status: select('Status', ['pending', 'approved', 'rejected', 'completed']) } },
  applications: { title: 'Applications', table: 'job_applications', fields: { job_id: text('Job', true, { type: 'relation', resource: 'careers' }), job_title: text('Job title'), name: text('Name', true), email: email(), phone: text('Phone', true), portfolio_link: text('Portfolio URL', false, { type: 'url' }), message: long('Message'), status: select('Status', ['pending', 'reviewed', 'shortlisted', 'rejected', 'hired']) } },
  users: { title: 'Users', fields: { name: text('Name', true), email: email(), phone: text('Phone', true), password: text('Password (leave blank to keep on edit)', false, { type: 'password' }), role: text('Role', true, { type: 'role', default: 'user' }) } },
  roles: { title: 'Roles', fields: { name: text('Role name', true), description: long('Description'), admin_access: select('Full dashboard access', ['0', '1']) } },
  orders: { title: 'Orders', fields: { user_id: number('User ID'), full_name: text('Customer name', true), phone: text('Phone', true), city: text('City', true), address: long('Address', true), payment_method: select('Payment method', ['mobile-money', 'cash']), status: select('Status', ['pending', 'confirmed', 'delivered', 'cancelled']), items: text('Order items', true, { type: 'items' }) } },
};
module.exports = resources;
