import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, BookOpen, Film, ClipboardCheck, Pencil, Trash2 } from 'lucide-react';
import api from '../Utils/api';
import useRemote from '../Utils/useRemote';
import DataState from '../Components/DataState';
import { contentChanged } from '../Utils/session';
const input = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900';
const primary = 'rounded-xl bg-purple-700 px-4 py-2 font-bold text-white disabled:opacity-50';
function Field({ label, children }) { return <label className="block text-sm font-semibold text-slate-700">{label}{children}</label>; }
function MediaField({ label, value, onChange, video, onBusy }) {
  const [progress, setProgress] = useState(null);
  const [error, setError] = useState('');
  const [preview, setPreview] = useState(null);
  useEffect(() => { let active = true; if (value?.startsWith('/learning-media/')) api.post('/admin/learning/media/sign', { path: value }).then(response => { if (active) setPreview({ path: value, url: response.data.url }); }).catch(() => {}); return () => { active = false; }; }, [value]);
  async function upload(file) {
    if (!file) return;
    const limit = (video ? 250 : 5) * 1024 * 1024;
    if (file.size > limit) { setError(`Maximum file size: ${video ? '250' : '5'} MB.`); return; }
    onBusy(true); setProgress(0); setError('');
    try { const response = await api.post('/admin/learning/media', file, { headers: { 'Content-Type': file.type }, onUploadProgress: event => setProgress(Math.round(event.loaded / (event.total || file.size) * 100)) }); onChange(response.data.path); setPreview({ path: response.data.path, url: response.data.preview }); }
    catch (error) { setError(error.response?.data?.error || 'Upload failed. Please retry.'); }
    finally { setProgress(null); onBusy(false); }
  }
  const source = value?.startsWith('/learning-media/') ? preview?.path === value ? preview.url : '' : value;
  return <div className="space-y-2"><Field label={label}><input className={input} value={value || ''} onChange={event => onChange(event.target.value)} placeholder={video ? 'Direct MP4/WebM URL, or upload below' : 'Image URL, or upload below'} /></Field><input aria-label={`Upload ${label}`} type="file" disabled={progress !== null} accept={video ? 'video/mp4,video/webm' : 'image/png,image/jpeg,image/webp'} onChange={event => upload(event.target.files[0])} className="max-w-full text-sm" /><p className="text-xs text-slate-500">{video ? 'MP4 or WebM · up to 250 MB' : 'PNG, JPEG or WebP · up to 5 MB'}. Uploaded lesson media is private.</p>{progress !== null && <p role="status">Uploading: {progress}%</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{source && (video ? <video src={source} controls preload="metadata" className="mt-2 max-h-60 w-full rounded-lg bg-black" /> : <img src={source} alt="Content preview" className="mt-2 max-h-48 rounded-lg" />)}</div>;
}
function ContentEditor({ kind, record, courseId, modules, units, onClose, onSaved }) {
  const [form, setForm] = useState(() => ({ title: '', description: '', content: '', video_url: '', image_url: '', published: 0, position: 1, duration_minutes: 10, module_id: modules[0]?.id || '', course_id: courseId, kind: 'unit', unit_id: units[0]?.id || '', pass_mark: 70, time_limit_minutes: 30, max_attempts: 3, questions: [{ prompt: '', options: ['', ''], correct: 0, points: 1, explanation: '' }], ...record }));
  const [busy, setBusy] = useState(false);
  const [uploads, setUploads] = useState(0);
  const [error, setError] = useState('');
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const question = (index, key, value) => set('questions', form.questions.map((item, i) => i === index ? { ...item, [key]: value } : item));
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { if (record?.id) await api.put(`/admin/learning/${kind}/${record.id}`, form); else await api.post(`/admin/learning/${kind}`, form); contentChanged(); onSaved(); } catch (error) { setError(error.response?.data?.error || 'Unable to save content.'); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-purple-200 bg-white p-5 text-slate-900 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">{record?.id ? 'Edit' : 'Create'} {kind === 'assessments' ? 'assessment' : kind === 'units' ? 'learning unit' : 'module'}</h2><button disabled={busy || uploads > 0} onClick={onClose} className="text-sm font-semibold">Cancel</button></div><form onSubmit={submit} className="space-y-5"><Field label="Title"><input required className={input} maxLength={200} value={form.title} onChange={event => set('title', event.target.value)} /></Field>
    {kind !== 'assessments' && <div className="grid gap-4 sm:grid-cols-2"><Field label="Position in course / module"><input required type="number" min="1" className={input} value={form.position} onChange={event => set('position', Number(event.target.value))} /></Field>{kind === 'units' && <Field label="Estimated study time (minutes)"><input required type="number" min="1" max="1440" className={input} value={form.duration_minutes} onChange={event => set('duration_minutes', Number(event.target.value))} /></Field>}</div>}
    {kind === 'modules' && <Field label="Module introduction"><textarea className={input} rows="3" value={form.description} onChange={event => set('description', event.target.value)} /></Field>}
    {kind === 'units' && <><Field label="Module"><select required className={input} value={form.module_id} onChange={event => set('module_id', Number(event.target.value))}>{modules.map(module => <option key={module.id} value={module.id}>{module.title}</option>)}</select></Field><Field label="Lesson text, instructions and video transcript"><textarea className={input} rows="12" value={form.content} onChange={event => set('content', event.target.value)} placeholder="Explain the concepts, add examples, and give learners a practical task." /></Field><div className="grid gap-5 lg:grid-cols-2"><MediaField label="Video lesson" video value={form.video_url} onChange={value => set('video_url', value)} onBusy={value => setUploads(count => count + (value ? 1 : -1))} /><MediaField label="Lesson image" value={form.image_url} onChange={value => set('image_url', value)} onBusy={value => setUploads(count => count + (value ? 1 : -1))} /></div></>}
    {kind === 'assessments' && <><div className="grid gap-4 sm:grid-cols-2"><Field label="Assessment type"><select disabled={!!record?.id} className={input} value={form.kind} onChange={event => set('kind', event.target.value)}><option value="unit">Unit assessment</option><option value="exam">Course final exam</option></select></Field>{form.kind === 'unit' && <Field label="Learning unit"><select required disabled={!!record?.id} className={input} value={form.unit_id} onChange={event => set('unit_id', Number(event.target.value))}><option value="">Choose a unit</option>{units.map(unit => <option key={unit.id} value={unit.id}>{unit.title}</option>)}</select></Field>}</div><div className="grid gap-4 sm:grid-cols-3">{[['pass_mark','Pass mark (%)',100],['time_limit_minutes','Time limit (minutes)',240],['max_attempts','Allowed attempts',20]].map(([key,label,max]) => <Field key={key} label={label}><input required type="number" min="1" max={max} className={input} value={form[key]} onChange={event => set(key, Number(event.target.value))} /></Field>)}</div>
    <div className="space-y-5">{form.questions.map((item,index) => <fieldset key={index} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="mb-4 flex justify-between"><h3 className="font-bold">Question {index + 1}</h3><button type="button" disabled={form.questions.length === 1} className="text-sm text-red-700 disabled:opacity-30" onClick={() => set('questions', form.questions.filter((_,i) => i !== index))}>Remove question</button></div><Field label="Question"><textarea required className={input} value={item.prompt} onChange={event => question(index,'prompt',event.target.value)} /></Field><div className="my-4 space-y-2">{item.options.map((option,optionIndex) => <div key={optionIndex} className="flex items-center gap-3"><input type="radio" name={`correct-${index}`} aria-label={`Mark option ${optionIndex + 1} correct for question ${index + 1}`} checked={item.correct === optionIndex} onChange={() => question(index,'correct',optionIndex)} className="accent-purple-700" /><input aria-label={`Question ${index + 1}, option ${optionIndex + 1}`} required className={input} value={option} onChange={event => question(index,'options',item.options.map((value,i) => i === optionIndex ? event.target.value : value))} /><button type="button" aria-label={`Remove option ${optionIndex + 1}`} disabled={item.options.length <= 2} onClick={() => set('questions', form.questions.map((q,i) => i === index ? { ...q, options: q.options.filter((_,j) => j !== optionIndex), correct: q.correct === optionIndex ? 0 : q.correct > optionIndex ? q.correct - 1 : q.correct } : q))} className="text-red-700 disabled:opacity-30">×</button></div>)}</div><button type="button" disabled={item.options.length >= 6} className="text-sm font-bold text-purple-700 disabled:opacity-30" onClick={() => question(index,'options',[...item.options,''])}>+ Add answer option</button><p className="mt-2 text-xs text-slate-500">Select the radio button beside the correct answer. Use two options for true/false questions.</p><div className="mt-4 grid gap-4 sm:grid-cols-[120px_1fr]"><Field label="Marks"><input required type="number" min="1" max="100" className={input} value={item.points} onChange={event => question(index,'points',Number(event.target.value))} /></Field><Field label="Explanation shown after passing"><textarea className={input} value={item.explanation} onChange={event => question(index,'explanation',event.target.value)} /></Field></div></fieldset>)}</div><button type="button" className="rounded-lg border border-purple-200 px-4 py-2 font-bold text-purple-700" onClick={() => set('questions',[...form.questions,{ prompt:'', options:['',''], correct:0, points:1, explanation:'' }])}>+ Add question</button></>}
    <label className="flex items-center gap-3 rounded-xl bg-purple-50 p-4 font-semibold"><input type="checkbox" checked={!!form.published} onChange={event => set('published',event.target.checked ? 1 : 0)} className="accent-purple-700" />Publish for students</label><p className="text-xs text-slate-500">Keep unfinished content as drafts. Students need a published assessment for each unit and a published final exam to earn a certificate.</p>{error && <p role="alert" className="text-red-700">{error}</p>}<button disabled={busy || uploads > 0} className={primary}>{uploads ? 'Wait for uploads…' : busy ? 'Saving…' : 'Save content'}</button></form></section>;
}
function Builder({ courseId }) {
  const remote = useRemote(`/admin/learning/courses/${courseId}`, null);
  const [editor, setEditor] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [error,setError] = useState('');
  const [busy,setBusy] = useState(false);
  const data = remote.data;
  async function remove() { setBusy(true); setError(''); try { await api.delete(`/admin/learning/${deleting.kind}/${deleting.record.id}`); setDeleting(null); contentChanged(); remote.reload(); } catch(error) { setError(error.response?.data?.error || 'Unable to delete.'); } finally { setBusy(false); } }
  const actions = (kind,record) => <div className="flex shrink-0 gap-3"><button aria-label={`Edit ${record.title}`} onClick={() => setEditor({ kind,record })} className="text-purple-700"><Pencil size={16} /></button><button aria-label={`Delete ${record.title}`} onClick={() => setDeleting({ kind,record })} className="text-red-600"><Trash2 size={16} /></button></div>;
  return <div className="space-y-5"><DataState {...remote} />{error && <p role="alert" className="text-red-600">{error}</p>}{deleting && <div role="alertdialog" aria-label="Delete learning content" className="rounded-xl bg-red-50 p-5 text-red-900"><p>Delete “{deleting.record.title}”? Its dependent units, assessments and attempts will also be removed. Unpublish instead to retain student records.</p><div className="mt-3 flex gap-4"><button disabled={busy} onClick={remove} className="font-bold">Confirm deletion</button><button onClick={() => setDeleting(null)}>Cancel</button></div></div>}{data && <>{editor && <ContentEditor key={`${editor.kind}-${editor.record?.id || 'new'}`} {...editor} courseId={courseId} modules={data.modules} units={data.units} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); remote.reload(); }} />}
    <div className="flex flex-wrap gap-3"><button className={primary} onClick={() => setEditor({kind:'modules',record:null})}><Plus size={16} className="mr-2 inline" />Add module</button><button disabled={!data.units.length} className="rounded-xl border border-purple-300 bg-white px-4 py-2 font-bold text-purple-700 disabled:opacity-50" onClick={() => setEditor({kind:'assessments',record:null})}><ClipboardCheck size={16} className="mr-2 inline" />Add assessment / exam</button></div>
    {!data.modules.length && <div className="rounded-2xl border border-dashed border-purple-200 bg-white p-10 text-center text-slate-600"><BookOpen className="mx-auto mb-3 text-purple-600" /><h2 className="text-xl font-bold">Build a course learners can finish</h2><p className="mt-3">Start with a module, add short units, then create a practice assessment for every unit and a final exam.</p></div>}
    {data.modules.map(module => <section key={module.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white text-slate-900"><div className="flex items-center justify-between gap-4 border-b border-slate-100 bg-slate-50 p-5"><div><p className="text-xs font-bold text-purple-600">MODULE {module.position} · {module.published ? 'PUBLISHED' : 'DRAFT'}</p><h2 className="mt-1 text-lg font-bold">{module.title}</h2></div>{actions('modules',module)}</div><div className="space-y-3 p-5">{data.units.filter(unit=>unit.module_id===module.id).map(unit=><div key={unit.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-4"><div><p className="font-semibold"><Film size={15} className="mr-2 inline text-purple-600" />{unit.position}. {unit.title}</p><p className="mt-1 text-xs text-slate-500">{unit.duration_minutes} min · {unit.published?'Published':'Draft'} · {data.assessments.some(a=>a.unit_id===unit.id && a.published)?'Assessment ready':'Needs published assessment'}</p></div>{actions('units',unit)}</div>)}<button className="text-sm font-bold text-purple-700" onClick={()=>setEditor({kind:'units',record:{module_id:module.id,position:data.units.filter(unit=>unit.module_id===module.id).length+1}})}>+ Add learning unit</button></div></section>)}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-900"><h2 className="mb-4 text-xl font-bold">Assessments & final exam</h2>{!data.assessments.length && <p className="text-slate-500">No assessments yet.</p>}<div className="space-y-3">{data.assessments.map(assessment=><div key={assessment.id} className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p className="font-bold">{assessment.title}</p><p className="mt-1 text-xs text-slate-500">{assessment.kind==='exam'?'Final exam':'Unit assessment'} · {assessment.questions.length} questions · {assessment.pass_mark}% to pass · {assessment.time_limit_minutes} min · {assessment.published?'Published':'Draft'}</p></div>{actions('assessments',assessment)}</div>)}</div></section>
  </>}</div>;
}
export default function AdminLearning() {
  const courses = useRemote('/admin/courses'); const [selected,setSelected]=useState(''); const id = selected || courses.data[0]?.id;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Learning studio</h1><p className="mt-1 text-sm text-slate-500">Create focused modules, video lessons and assessments.</p></div><Link to="/admin/students" className="rounded-xl border px-4 py-2 font-bold text-purple-600">Student progress →</Link></div><DataState {...courses} />{courses.data.length ? <><label className="block text-sm font-bold">Choose course<select className={`${input} max-w-xl`} value={id} onChange={event=>setSelected(Number(event.target.value))}>{courses.data.map(course=><option key={course.id} value={course.id}>{course.title}</option>)}</select></label><Builder key={id} courseId={Number(id)} /></> : !courses.loading && <p>Create a course in <Link to="/admin/courses" className="font-bold text-purple-600">Courses</Link> before adding its learning content.</p>}</div>;
}
