import { useState } from 'react';
import { Link } from 'react-router-dom';
import useRemote from '../Utils/useRemote';
import api from '../Utils/api';
import DataState from '../Components/DataState';
export default function AdminStudents() {
  const remote = useRemote('/admin/learning/students', null); const data = remote.data;
  const [search,setSearch]=useState(''); const [message,setMessage]=useState(''); const [activation,setActivation]=useState(''); const [busy,setBusy]=useState(false); const [tab,setTab]=useState('enrollments');
  async function action(url,body,method='post') { setBusy(true);setMessage('');setActivation('');try{const response=await api[method](url,body);setMessage(response.data.message || (response.data.configured===false?'SMTP is not configured. Use an activation link or configure email delivery.':`Completed. ${response.data.sent ?? ''} messages sent.`));setActivation(response.data.activation_url || '');remote.reload();}catch(error){setMessage(error.response?.data?.error || 'Unable to complete this action.');}finally{setBusy(false);}}
  const rows = data?.enrollments.filter(row=>`${row.full_name} ${row.email} ${row.course_title}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Students & progress</h1><p className="mt-1 text-sm text-slate-500">Approve applicants, follow learning progress and celebrate completion.</p></div><Link to="/admin/learning" className="font-bold text-purple-600">Learning studio →</Link></div><DataState {...remote} />{data && <><div className="flex flex-wrap gap-4 rounded-2xl border border-purple-200 bg-purple-50 p-5 text-purple-900"><div className="flex-1"><p className="font-bold">{data.email_configured?'Automatic email delivery is configured':'Account activation links are ready to share'}</p><p className="mt-1 text-sm">{data.email_configured?`${data.notifications.pending} messages awaiting delivery.`:'SMTP has not been configured. Approval still creates accounts; use Copy activation link to send students their secure setup link.'}</p></div><button disabled={busy} onClick={()=>action('/admin/learning/notifications/retry')} className="font-bold">Retry email delivery</button></div>{message && <p role="status" className="rounded-xl border border-purple-200 bg-white p-4 text-slate-800">{message}</p>}{activation && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-slate-900"><label className="block text-sm font-bold">Student activation link · expires in 48 hours<input readOnly value={activation} className="mt-2 w-full rounded border bg-white p-3 font-mono text-xs" /></label><button onClick={()=>navigator.clipboard.writeText(activation).then(()=>setMessage('Activation link copied.')).catch(()=>setMessage('Select and copy the link above.'))} className="mt-3 font-bold text-emerald-700">Copy activation link</button></div>}
    <div className="flex flex-wrap gap-2">{[['enrollments','Enrollments'],['results','Assessment results'],['certificates','Certificates']].map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={`rounded-xl px-4 py-2 font-bold ${tab===value?'bg-purple-700 text-white':'border bg-white text-slate-600'}`}>{label}</button>)}</div>
    {tab==='enrollments' && <><input aria-label="Search students" className="w-full rounded-xl border bg-white p-3 text-slate-900" placeholder="Search name, email or course…" value={search} onChange={event=>setSearch(event.target.value)} /><div className="space-y-4">{rows.map(row=><article key={row.id} className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">{row.full_name}</h2><p className="text-sm text-slate-500">{row.email} · {row.phone}</p><p className="mt-2 font-semibold text-purple-700">{row.course_title}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{row.status}</span></div><div className="my-4 flex items-center gap-4"><progress className="h-2 w-64 max-w-[65%] accent-purple-700" value={row.progress.completed} max={row.progress.total||1} /><span className="text-xs">{row.progress.completed}/{row.progress.total} units completed</span></div><div className="flex flex-wrap gap-3 text-sm font-bold">{row.status==='pending' && <><button disabled={busy} onClick={()=>action(`/admin/learning/enrollments/${row.id}/approve`)} className="rounded-lg bg-purple-700 px-4 py-2 text-white">Approve & create account</button><button disabled={busy} onClick={()=>action(`/admin/enrollments/${row.id}/status`,{status:'rejected'},'patch')} className="rounded-lg border px-4 py-2 text-red-600">Reject</button></>}{['approved','completed'].includes(row.status) && (row.account_active ? <span className="self-center text-emerald-700">Account active ✓</span> : <button disabled={busy} onClick={()=>action(`/admin/learning/enrollments/${row.id}/invite`)} className="rounded-lg border border-purple-200 px-4 py-2 text-purple-700">Create new activation link</button>)}<Link to="/admin/enrollments" className="self-center text-slate-500">Edit enrollment details</Link></div></article>)}{!rows.length && <p className="p-8 text-center text-slate-500">No enrollment applications found.</p>}</div></>}
    {tab==='results' && <div className="overflow-auto rounded-2xl bg-white text-slate-900"><table className="w-full text-left text-sm"><thead><tr>{['Student','Assessment','Mark','Status','Support'].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{data.attempts.map(attempt=><tr key={attempt.id} className="border-t border-slate-100"><td className="p-4">{attempt.name}</td><td className="p-4">{attempt.title}</td><td className="p-4">{attempt.score===null?'—':`${attempt.score}%`}</td><td className="p-4">{attempt.submitted_at?attempt.passed?'Passed':'Not passed':new Date(attempt.expires_at)<new Date()?'Expired':'In progress'}</td><td className="p-4"><button disabled={busy} className="font-bold text-purple-700" onClick={()=>action('/admin/learning/attempts/allow',{user_id:attempt.user_id,assessment_id:attempt.assessment_id})}>Grant another attempt</button></td></tr>)}</tbody></table>{!data.attempts.length && <p className="p-8 text-center text-slate-500">No assessments attempted yet.</p>}</div>}
    {tab==='certificates' && <div className="grid gap-4 md:grid-cols-2">{data.certificates.map(cert=><article key={cert.id} className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-900"><h2 className="font-bold">{cert.student_name}</h2><p className="mt-1 text-slate-500">{cert.course_title}</p><p className="my-3 text-sm">{cert.score}% · {new Date(cert.issued_at).toLocaleDateString()} · {cert.revoked_at?'Revoked':'Valid'}</p><div className="flex gap-4 text-sm font-bold"><Link to={`/certificates/${cert.code}`} className="text-purple-700">View certificate</Link><button disabled={busy} className="text-red-600" onClick={()=>action(`/admin/learning/certificates/${cert.id}`,{revoked:!cert.revoked_at},'patch')}>{cert.revoked_at?'Restore certificate':'Revoke certificate'}</button></div></article>)}{!data.certificates.length && <p className="text-slate-500">Certificates appear when students pass their final exams.</p>}</div>}
  </>}</div>;
}
