import { useEffect, useRef, useState } from 'react';
import './practice.css';
export default function PhpExecution({source,tests=[]}){
  const [stdin,setStdin]=useState('');const[result,setResult]=useState(null);const[status,setStatus]=useState('');const[error,setError]=useState('');const worker=useRef(null);const timer=useRef(null);
  useEffect(()=>()=>{worker.current?.terminate();clearTimeout(timer.current);},[]);
  function stop(message='Execution stopped.'){worker.current?.terminate();worker.current=null;clearTimeout(timer.current);setStatus('');setError(message);}
  function run(){worker.current?.terminate();clearTimeout(timer.current);setResult(null);setError('');setStatus('Loading PHP 8.4…');const instance=new Worker(new URL('./php.worker.js',import.meta.url),{type:'module'});worker.current=instance;
    timer.current=setTimeout(()=>stop('PHP could not load in time. Check your connection and try again.'),60000);
    instance.onmessage=event=>{if(worker.current!==instance)return;if(event.data.type==='ready'){clearTimeout(timer.current);setStatus('Running PHP…');timer.current=setTimeout(()=>stop('Execution stopped after 5 seconds. Check for an infinite loop.'),5000);}else if(event.data.type==='result'){clearTimeout(timer.current);setResult(event.data.results);setStatus('');instance.terminate();worker.current=null;}else if(event.data.type==='error')stop(event.data.error);};
    instance.onerror=()=>stop('PHP could not start. Please use a current browser and retry.');instance.postMessage({source,stdin,tests});
  }
  return <section className="practice-card"><div className="practice-actions mb-3"><h2 className="!mb-0">PHP 8.4 lab</h2><span className="practice-badge">Runs in your browser</span></div><p className="practice-muted mb-4">Write real PHP, including the &lt;?php opening tag. Read input with fgets(STDIN) or file_get_contents('php://input'). Files are temporary; database servers and external requests are unavailable.</p><label className="practice-field">Program input<textarea aria-label="PHP program input" rows="3" maxLength="10000" value={stdin} onChange={event=>setStdin(event.target.value)}/></label>{tests.length>0&&<p className="practice-muted mb-3">This task’s self-tests use their own inputs.</p>}<div className="practice-actions"><button className="practice-button" disabled={!!status||!source.trim()} onClick={run}>Run PHP & tests</button>{status&&<button className="practice-button secondary" onClick={()=>stop()}>Stop PHP</button>}<span role="status" className="practice-muted">{status}</span></div>{error&&<p role="alert" className="practice-notice practice-error mt-4">{error}</p>}{result?.map((item,index)=><div key={index} className={`practice-test ${item.passed?'pass':'fail'}`}><strong>{item.label} · {item.passed?'Passed':'Needs attention'}</strong><pre className="practice-console mt-3">{item.actual||'No output'}</pre>{item.error&&<pre className="practice-notice practice-error mt-2">{item.error}</pre>}{item.expected!==undefined&&<p className="practice-muted mt-2">Expected: <code className="whitespace-pre-wrap">{item.expected}</code></p>}</div>)}</section>;
}
