import { useEffect, useState } from 'react';
import LearningShell from './LearningShell';
import useRemote from '../Utils/useRemote';
import DataState from '../Components/DataState';
import { getUser } from '../Utils/session';
import CodeEditor from './CodeEditor';
import RemoteExecution from './RemoteExecution';
import './practice.css';
function Project({language,userId}){
  const key=`coderwanda-playground-${userId}-${language.id}`;
  const[code,setCode]=useState(()=>{try{return localStorage.getItem(key)||'';}catch{return '';}});const[status,setStatus]=useState('Draft stays in this browser.');
  useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(key,code);setStatus('Saved in this browser');}catch{setStatus('Browser storage is full. Download your code to keep it.');}},800);return()=>clearTimeout(timer);},[code,key]);
  return <div className="practice-stack"><section className="practice-card"><div className="practice-actions mb-4"><h2 className="!mb-0">{language.name}</h2><span className="practice-muted ml-auto">{status}</span></div><CodeEditor files={{main:code}} active="main" onActive={()=>{}} onChange={files=>setCode(files.main)}/><button className="practice-button secondary mt-4" onClick={()=>{const url=URL.createObjectURL(new Blob([code],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download='coderwanda-source.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download code</button></section><RemoteExecution key={language.id} languageId={language.id} source={code}/></div>;
}
export default function Playground(){const remote=useRemote('/practice/languages',null);const[selected,setSelected]=useState('');const[search,setSearch]=useState('');const language=remote.data?.languages.find(item=>String(item.id)===selected)||remote.data?.languages[0];return <LearningShell><div className="practice-page"><div className="practice-hero"><p className="practice-kicker">CodeRwanda coding playground</p><h1>A place to try your next idea.</h1><p>Choose a language, write a program, provide input and inspect the output. Practice freely between lessons.</p></div><DataState {...remote}/>{remote.data&&!remote.data.configured&&<div className="practice-card"><h2>The multi-language runner is being prepared</h2><p className="practice-muted">Your administrator needs to start the local execution service. Its available languages will appear here automatically. JavaScript and HTML/CSS practical tasks already run inside your lessons.</p></div>}{language&&<><div className="practice-columns"><label className="practice-field">Find a language<input placeholder="Python, Java, C++, SQL…" value={search} onChange={event=>setSearch(event.target.value)}/></label><label className="practice-field">Language and runtime<select aria-label="Programming language" value={language.id} onChange={event=>setSelected(event.target.value)}>{remote.data.languages.filter(item=>item.id===language.id||item.name.toLowerCase().includes(search.toLowerCase())).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><Project key={language.id} language={language} userId={getUser()?.id}/></>}</div></LearningShell>;}
