import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Play, Send, Code2, MessageCircle, CheckCircle2 } from 'lucide-react';
import api from '../Utils/api';
import useRemote from '../Utils/useRemote';
import DataState from '../Components/DataState';
import LearningShell from './LearningShell';
import CodeEditor from './CodeEditor';
import RemoteExecution from './RemoteExecution';
import { runnerDocument } from './practiceRunner';
import './practice.css';

function Feedback({ submission }) {
  const [active,setActive]=useState(Object.keys(submission.files)[0]);
  return <details className="practice-card"><summary>Submission #{submission.id} · {submission.status==='reviewed'?`${submission.score}% · ${submission.passed?'Passed':'Keep improving'}`:'Awaiting trainer review'}</summary><p className="practice-muted">Submitted {new Date(submission.submitted_at).toLocaleString()} · Task version {submission.version}</p>{submission.feedback && <><p className={`practice-notice ${submission.passed?'practice-success':''}`}>{submission.feedback}</p><p className="practice-muted">Reviewed by {submission.reviewer_name || 'your trainer'}</p><div className="my-4">{submission.snapshot.rubric.map((item,index)=><p key={index} className="practice-muted">{item.label}: <strong>{submission.marks?.[index]} / {item.points}</strong></p>)}</div></>}<CodeEditor files={submission.files} active={active} onActive={setActive} readOnly annotations={submission.annotations||[]} />{submission.annotations?.map((item,index)=><div key={index} className={`review-comment ${item.kind}`}><button className="font-bold text-sm" onClick={()=>setActive(item.file)}>{item.file}:{item.line} · {item.kind}</button><p>{item.message}</p></div>)}</details>;
}
function Workspace({ initial, reload }) {
  const { exercise } = initial;
  const [files,setFiles]=useState(initial.draft?.files || exercise.starter);
  const [active,setActive]=useState(Object.keys(files)[0]);
  const revision=useRef(initial.draft?.revision || 0);const saved=useRef(JSON.stringify(files));const saving=useRef(false);const blocked=useRef(false);
  const [saveStatus,setSaveStatus]=useState(initial.draft?'Draft saved':'Starter code');
  const [error,setError]=useState('');const [message,setMessage]=useState('');const [reflection,setReflection]=useState('');const [busy,setBusy]=useState(false);
  const [run,setRun]=useState(null);const [result,setResult]=useState(null);const frame=useRef(null);
  const save=async current=>{
    const encoded=JSON.stringify(current);if(encoded===saved.current||saving.current||blocked.current)return;
    saving.current=true;setSaveStatus('Saving…');
    try{const response=await api.put(`/practice/exercises/${exercise.id}/draft`,{files:current,revision:revision.current});revision.current=response.data.revision;saved.current=encoded;setSaveStatus('Draft saved');}
    catch(error){if(error.response?.status===409)blocked.current=true;setSaveStatus(error.response?.data?.error||'Not saved — check your connection, then click Save draft.');}
    finally{saving.current=false;}
  };
  // An explicit save is available when offline or when another tab changed the draft.
  useEffect(()=>{const timer=setTimeout(()=>{void save(files);},900);return()=>clearTimeout(timer);});
  useEffect(()=>{const warn=event=>{if(JSON.stringify(files)!==saved.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[files]);
  useEffect(()=>{
    if(!run)return;
    const receive=event=>{if(event.source!==frame.current?.contentWindow||event.data?.type!=='coderwanda-run'||event.data.token!==run.token)return; const data=event.data; if(!Array.isArray(data.logs)||!Array.isArray(data.results))return;setResult({logs:data.logs.slice(0,100).map(value=>String(value).slice(0,2000)),results:data.results.slice(0,30),error:data.error?String(data.error).slice(0,2000):''});};
    window.addEventListener('message',receive);const timer=setTimeout(()=>setResult(previous=>previous||{logs:[],results:[],error:'Runner did not respond. Try again in a current browser.'}),6000);
    return()=>{window.removeEventListener('message',receive);clearTimeout(timer);};
  },[run]);
  function execute(){const token=crypto.randomUUID();setResult(null);setRun({token,document:runnerDocument(files,exercise.tests,exercise.language,token)});}
  async function submit(){setBusy(true);setError('');setMessage('');try{await save(files);const response=await api.post(`/practice/exercises/${exercise.id}/submit`,{files,reflection,version:exercise.version});setMessage(response.data.message);reload();}catch(error){setError(error.response?.data?.error||'Unable to submit your work.');}finally{setBusy(false);}}
  const pending=initial.submissions.some(item=>item.status==='submitted');
  return <div className="practice-page"><div className="practice-actions"><Link to={`/learn/courses/${exercise.course_id}`} className="font-bold text-purple-700">← Back to course</Link><Link className="ml-auto text-sm font-bold text-purple-700" to={`/learn/courses/${exercise.course_id}/chat?help=1`}><MessageCircle size={16} className="inline mr-2" />Ask a trainer</Link></div><div className="practice-hero"><p className="practice-kicker">CodeRwanda practice lab / {exercise.unit_title}</p><h1>{exercise.title}</h1><p>Build it. Test your thinking. Improve with feedback.</p><div className="practice-actions mt-4"><span className="practice-badge">{exercise.language_name || (exercise.language==='web'?'HTML · CSS · JavaScript':'JavaScript')}</span><span className="practice-badge">{exercise.required?'Required practical':'Practice challenge'}</span><span className="practice-badge">{exercise.pass_mark}% to pass</span></div></div>
    <div className="practice-grid"><aside className="practice-stack"><section className="practice-card"><h2>Your challenge</h2><p className="whitespace-pre-wrap text-sm">{exercise.instructions}</p></section><section className="practice-card"><h2>How you are marked</h2>{exercise.rubric.map((item,index)=><div className="studio-row text-sm" key={index}><span>{item.label}</span><strong>{item.points} marks</strong></div>)}<p className="practice-muted mt-4">Self-tests help you practice. Your trainer awards the official mark using this rubric and your submitted code.</p></section><section className="practice-card"><h2>Make mistakes. Make progress.</h2><ol className="text-sm space-y-3"><li>1. Read the task and marking criteria.</li><li>2. Write code, run it, inspect failures.</li><li>3. Explain your approach and submit.</li><li>4. Use trainer feedback to improve.</li></ol></section></aside>
    <div className="practice-stack"><section className="practice-card"><div className="practice-actions mb-4"><h2 className="!mb-0"><Code2 size={20} className="inline mr-2 text-purple-700" />Your workspace</h2><span role="status" className="practice-muted ml-auto">{saveStatus}</span></div><CodeEditor files={files} onChange={setFiles} active={active} onActive={setActive} /><div className="practice-actions mt-4">{!exercise.language.startsWith('judge0:') && <button className="practice-button" onClick={execute}><Play size={15} className="inline mr-2" />Run & test</button>}<button className="practice-button secondary" onClick={()=>save(files)}>Save draft</button><button className="text-sm font-bold text-slate-500" onClick={()=>{if(window.confirm('Replace your working code with the starter files? Submitted work will remain available.')){setFiles(exercise.starter);setRun(null);setResult(null);}}}>Reset to starter</button>{run&&<button className="text-sm font-bold text-slate-500" onClick={()=>{setRun(null);setResult(null);}}>Stop / clear</button>}</div></section>
    {exercise.language.startsWith('judge0:') && <RemoteExecution exerciseId={exercise.id} source={files.main || ''} />}
    {run&&<section className="practice-card"><h2>{exercise.language==='web'?'HTML / CSS preview':'Execution'}</h2>{exercise.language==='web'&&<p className="practice-muted mb-3">HTML and CSS render here. JavaScript runs separately in the console without DOM access. External resources and network requests are disabled.</p>}<iframe key={run.token} ref={frame} title="Isolated code preview" sandbox="allow-scripts" referrerPolicy="no-referrer" srcDoc={run.document} className={exercise.language==='web'?'practice-preview':'h-20 w-full border-0'} /><h3 className="mt-4 mb-2">Console</h3><div className="practice-console" role="log">{result?result.logs.join('\n')||'No console output.':'Running…'}{result?.error&&<p className="text-rose-300 mt-2">{result.error}</p>}</div><h3 className="mt-4">Self-test results</h3>{!exercise.tests.length&&<p className="practice-muted">No automated self-tests for this task. Follow the rubric before submitting.</p>}{result?.results.map((test,index)=><div key={index} className={`practice-test ${test.passed?'pass':'fail'}`}><strong>{test.passed?'✓':'×'} {String(test.label)}</strong><p>{test.error?String(test.error):`Expected: ${String(test.expected)} · Received: ${String(test.actual)}`}</p></div>)}</section>}
    <section className="practice-card"><h2>Ready for a code review?</h2><label className="practice-field">Explain your approach, what you tested, and where you need help<textarea rows="3" maxLength="4000" value={reflection} onChange={event=>setReflection(event.target.value)} /></label>{error&&<p role="alert" className="practice-notice practice-error mb-3">{error}</p>}{message&&<p role="status" className="practice-notice practice-success mb-3">{message}</p>}<button className="practice-button" disabled={busy||pending} onClick={submit}><Send size={15} className="inline mr-2" />{pending?'Awaiting trainer review':busy?'Submitting…':'Submit for review'}</button><p className="practice-muted mt-3">Each submission keeps an exact copy of your code. You can keep practicing while you wait.</p></section>
    <section><h2 className="font-bold text-xl mb-4"><CheckCircle2 size={20} className="inline mr-2 text-purple-700" />Your feedback journey</h2><div className="practice-stack">{initial.submissions.map(item=><Feedback key={item.id} submission={item} />)}{!initial.submissions.length&&<p className="practice-notice">Your trainer’s marks, code comments and suggestions will appear here after your first review.</p>}</div></section></div></div></div>;
}
export default function PracticeWorkspace(){const{exerciseId}=useParams();const remote=useRemote(`/practice/exercises/${exerciseId}`,null);return <LearningShell><DataState {...remote}/>{remote.data&&<Workspace key={exerciseId} initial={remote.data} reload={remote.reload}/>}</LearningShell>;}
