JUDGE0_TELEMETRY_ENABLE=false
REDIS_HOST=redis
REDIS_PASSWORD=d09198c723e274f2a380e037118effd8073050524b326a56702db3debfe8b631
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=f1abdf67b03aa465120a6922eb8a0e208f829a6faacaaa1d69cf275090132b1d
AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=6dd7c4d3e681c1dfaf2055ac7e9ce1f85a9946b1bc8dc1a23a84702df508b5bf
ENABLE_NETWORK=false
ALLOW_ENABLE_NETWORK=false
ENABLE_CALLBACKS=false
ENABLE_ADDITIONAL_FILES=false
ENABLE_COMPILER_OPTIONS=false
ENABLE_COMMAND_LINE_ARGUMENTS=false
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=10
COUNT=2
MAX_QUEUE_SIZE=100
CPU_TIME_LIMIT=3
MAX_CPU_TIME_LIMIT=3
WALL_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=10
MEMORY_LIMIT=256000
MAX_MEMORY_LIMIT=256000
MAX_FILE_SIZE=512
MAX_MAX_FILE_SIZE=512
SECRET_KEY_BASE=5c987f40043c754acc7f4087ea16c3f31b273cecc54eded288bfb435e0671fb4a6cdf3159f450917032a8b6dd79eb40976260f85694c18f72565ff55d9b3bec2
